### PR TITLE
Simplify RQ, add Alternate-Content-Length

### PR DESCRIPTION
**Pull request by igrigorik**
See commit for background.

/cc @mnot sanity check? :)

### CODE REVIEW

**Comment by yoavweiss** [comment]
Can we split the PR into two? I'm all for the RQ change (with nits), but not really sure what the Alternate-Content-Length change is all about :)

**Comment by mnot** [comment]
+1 to @yoavweiss - Alternate-Content-Length looks... dubious.

**Comment by mdwelsh** [comment]
We need some mechanism for a site or proxy to convey the content length of the "original" (unmodified) response body for the sake of allowing user agents to track and report on compression. Chrome uses X-Original-Content-Length for this; Opera has a similar header. Alternate-Content-Length or Original-Content-Length are intended to provide this information.

**Comment by igrigorik** [comment]
Moved `Alternate-Content-Length` into a separate pull: https://github.com/igrigorik/http-client-hints/pull/42

**Comment by yoavweiss** [comment]
Can you update the gh-pages branch? It's lagging behind, at least on this merged PR

**Comment by igrigorik** [comment]
@yoavweiss yep, done: http://igrigorik.github.io/http-client-hints/#the-rq-client-hint

**Comment by yoavweiss** [comment]
Thanks! :)

**Pull request merged**
