### PR TITLE
Alternate-Content-Length for reporting data savings

### PR DESCRIPTION
**Pull request by igrigorik**
A mechanism to help the client estimate byte savings when advertised
hints are used by the server (origin or proxy) to select and deliver an optimized
response.

An optimizing proxy needs a way to convey the content length of the
alternate (unmodified) response body to allow the user agent to track
and report compression savings. Today, Chrome uses
X-Original-Content-Length for this, and Opera has a similar header.

### CODE REVIEW

**Comment by yoavweiss** [comment]
Can we clarify what that value means?

Let's say I'm operating a compression proxy that changes its compression settings according to that signal (so that without RQ, compression aims to be "invisible", and with it, we can afford visible compression artifacts).

In that case, what's the original content length that we're referring to? The original image coming from the origin server? Or the image compressed with the previous settings (which bytesize we do not necessarily know, unless we want to perform the compression twice)?

**Comment by igrigorik** [comment]
@yoavweiss it's the size of the asset prior to applying any additional optimizations or transformations to it. This includes, but is not limited to, use of Client Hints.. e.g. my server/proxy recompresses all images at lower quality; recompresses images based on advertised RW, RQ, DPR, etc.

**Comment by yoavweiss** [comment]
Well, since that's not something that you can accurately know in all cases (e.g. the "modified compression settings" case), it might be worth while to note that it can be a rough estimate.

**Comment by igrigorik** [comment]
blink-dev thread with lots of good feedback and discussion: https://groups.google.com/a/chromium.org/forum/#!searchin/blink-dev/alternate/blink-dev/lj7wSXPBPWE/fE5UGl_2y1QJ

**Comment by igrigorik** [comment]
Migrating open issues to HTTP-WG repo. Let's continue this discussion on: https://github.com/httpwg/http-extensions/issues/140

**Pull request closed without merging**
